### ISSUE TITLE
How to enable multiple associated extensions

### ISSUE THREAD

**Issue by lifenglsf** [cmb69/setup-php-sdk#14]
i want to compile memcached for windows,memcached support igbinary and msgpack,how can i enable memcached and msgpack when configure

**Comment by cmb69** [comment]
There is no special support for dependent extensions (yet); you basically need to download their sources, and build manually (`phpize && configure && nmake`). See https://github.com/cmb69/php-ftw/blob/master/.github/workflows/install-pecl-dep.bat.
