### ISSUE TITLE
Document examples to build dlls for a release

### ISSUE THREAD

**Issue by TysonAndre** [cmb69/setup-php-sdk#18]
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release mentions that this can be setup to run when a release is published

- push/PR may also work for some projects, though it would make it more likely that end users might run code that isn't part of a project's stable release (or as a part of a PR that didn't end up getting merged), and would use more cpu/storage resources

I got this to work in https://github.com/TysonAndre/var_representation/actions/runs/3260935531 based on the examples in apcu - the resulting dll could be used with php in Wine.

- https://github.com/TysonAndre/var_representation/blob/0.1.4/.github/workflows/build_dlls.yml

**Comment by codemasher** [comment]
I'd argue that this is "opinionated and depends on the project" territory and not necessarily focus of this but a separate action, like "php-extension release" that could be included in the user's workflow file after build and packaging.

**Comment by cmb69** [comment]
Yes, too specific, and also not necessarily what we really want; while it is, of course, okay if DLLs are available from the extension repository, we should still try to provide the DLLs from the PECL page of the extensions (note that uploading to windows.php.net from where the DLLs are fetched is still possible). See a [former discussion about that](https://externals.io/message/114751).

See also [some preliminary work](https://github.com/cmb69/php-ftw/blob/master/.github/workflows/pecl.yml) on building PECL extensions from a centralized repository. Note that [var_representation](https://github.com/cmb69/php-ftw/blob/master/.github/workflows/pecl.ini#L31-L32) should already be supported there. I'm hoping to add support for building PECL extensions with non-core dependencies there, and possibly to even automate triggering of the build process and uploading to windows.php.net there; and of course to move that repo to the php organization.

**Comment by TysonAndre** [comment]
Oh. I see there was a post on the mailing list this month - https://marc.info/?l=php-windows&m=166513833102290&w=2 - I'd been confused since there had been no dll builds in the last few months, and wasn't sure if the dll build for php 8.1.0 stable was going to be repeated in 8.2.0

> I'm hoping to add support for building PECL extensions with non-core dependencies there, and possibly to even automate triggering of the build process and uploading to windows.php.net there; and of course to move that repo to the php organization.

https://windows.php.net/ was last updated 10 months ago in December 2021 - maybe there should be a blog post saying something along the lines of : the team is working on the long term plan of building DLLs for PECL extensions with a new CI process after the hardware failure, but it isn't ready yet? Other PECL authors or end users may have similar questions.

> (note that uploading to windows.php.net from where the DLLs are fetched is still possible). 

I haven't found documentation on the uploading process. While it'd be more convenient to have them uploaded by the php for Windows team, is it possible for PECL authors to upload PECLs to windows.php.net until then (if so, where is the process documented)?


My larger concern is https://pecl.php.net/package/ast , which has far more downloads and is used for https://github.com/phan/phan - for reference, the `configure` options I'd used was at https://github.com/nikic/php-ast/pull/234 (the steps were ordinary, just `--enable-ast`)

- I'd started testing this out with a smaller extension since I was unfamiliar with the process

**Comment by cmb69** [comment]
> https://windows.php.net/ was last updated 10 months ago in December 2021 - maybe there should be a blog post saying something along the lines of

Oh, right. I've did that now: https://github.com/php/web-windows/commit/f974845b186551866ac34665279cd39bcb6f58ff#diff-4649f5de2037acf02fccb80408d8503c32aef8f78e93f2c19a35e540846e4fb4

> is it possible for PECL authors to upload PECLs to windows.php.net until then

That FTP server is configured with an IP allow-list, and the operator (@sAnexeh) is unlikely to change that, so uploading will only be possible for a few people. And given that this is about *binaries*, and the recent rise of supply chain attacks, that appears to be a good thing.

And yeah, I see the urgency in providing DLLs again, especially since PHP 8.2 is close to GA, and a mass rebuild would need to be done.
