### ISSUE TITLE
Document steps to `set REPORT_EXIT_STATUS=1` to run unit tests in examples

### ISSUE THREAD

**Issue by TysonAndre** [cmb69/setup-php-sdk#19]
https://github.com/cmb69/setup-php-sdk/blob/master/run.ps1 supports php 7.1 and 7.0. In php 7.2, REPORT_EXIT_STATUS was enabled by default, but in php 7.1 and below, tests would fail but the exit code would be 0, and the workflow would unexpectedly pass.

I've dropped support for 7.1 a while ago, but other users of the workflow may still support it

https://docs.github.com/en/actions/learn-github-actions/environment-variables mentions `env:` can be used

**Comment by boontham33345** [comment]
Good

**Comment by cmb69** [comment]
Thank you! However, this action is superseded by https://github.com/php/setup-php-sdk, so please report any possible issues there. I'm going to archive this repo soon.
