### ISSUE TITLE
Optionally install dependency libraries

### ISSUE THREAD

**Issue by cmb69** [cmb69/setup-php-sdk#2]
All core deps or individual? What about PECL deps?

**Comment by cmb69** [comment]
Core dependency support available as of v0.3 (5c27dff2215363d96ff963fe6d20a7f0772107d6).

PECL dependencies not yet supported, though.

**Comment by codemasher** [comment]
Quick question: is there a way to get a full list of recent Windows compatible PECL dependencies? https://windows.php.net/downloads/pecl/deps/ looks hilariously outdated.

**Comment by cmb69** [comment]
> https://windows.php.net/downloads/pecl/deps/ looks hilariously outdated.

Indeed, but this is the latest we have. Unfortunately, none of the PECL deps builds have been automated so far (well, a few are in https://github.com/winlibs/winlib-builder), so updating might take considerable time.

**Comment by codemasher** [comment]
Thanks for the quick reply - I'll check out the winlib builder!
For now I'm gonna implement download for PECL libraries from php.net then, to ease [things like this](https://github.com/Imagick/imagick/blob/661405abe21d12003207bc8eb0963fafc2c02ee4/.github/workflows/windows.yml#L24-L27), then i'll try to wrap my head around the winlibs :)

**Comment by cmb69** [comment]
There is a simplistic build script for imagemagick: https://github.com/winlibs/winlib-builder/blob/master/.github/workflows/imagemagick.yml.

Other than that, a serious issue with the PECL deps is that there are no [series files](https://windows.php.net/downloads/php-sdk/deps/series/); this should better change.

**Comment by codemasher** [comment]
From what it looks to me as an outsider (a php user who prefers to code on a native Windows environment) is that native Windows builds other than core have very low priority or don't even exist; and now with Windows having a Linux subsystem that can run Linux extensions, i get the feeling that native builds for Windows will be abandoned entirely in the foreseeable future. So i get it *why* the PECL directories are outdated...

**Comment by cmb69** [comment]
This GH action is superseded by https://github.com/php/setup-php-sdk. Please report any issues there.
