### ISSUE TITLE
how to install multiple deps

### ISSUE THREAD

**Issue by lifenglsf** [cmb69/setup-php-sdk#8]
i want to install multiple extension
 ```strategy:
      matrix:
          version: ["7.4"]
          arch: [x64]
          ts: [ts]
          deps: [zlib,session]
```

i used deps: [zlib,session] then it created two jobs

**Comment by cmb69** [comment]
`deps` is an input argument of `cmb69/setup-php-sdk`. See https://github.com/php/pecl-networking-xmlrpc/blob/dfe9120a9765599d383a829e48efc3715ce2f83a/.github/workflows/ci.yml#L19-L24 for an example.
